FROM balenalib/%%BALENA_MACHINE_NAME%%-python:3-bookworm

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . .

CMD ["python3", "door-motor.py"]
